### ISSUE TITLE
Loading Data Set on Shared File System

### ISSUE THREAD

**Issue by edwardbadboy** [intel/caffe#154] opened 2017-12-11 04:27 UTC
Hi! I'm testing multi-node training. We put the data on a shared file system (GlusterFS), and mount it on all the nodes. We find that when multiple Caffe instances try to open the same LMDB file, Caffe will stuck on opening the LMDB file.

After investigation we find that LMDB uses flock on the database file. On the LMDB official site, it does not recommend to be used on a shared file system. Then I try to use ALLOW_LMDB_NOLOCK=1 to compile Intel Caffe, and hope it skip locking the LMDB file, but it still gets stuck.

As I can see in the code, if ALLOW_LMDB_NOLOCK is set, in src/caffe/util/db_lmdb.cpp, the logic is as follow.

```
  if (mode == READ) {
    flags = MDB_RDONLY | MDB_NOTLS;
  }
  int rc = mdb_env_open(mdb_env_, source.c_str(), flags, 0664);
#ifndef ALLOW_LMDB_NOLOCK
  MDB_CHECK(rc);
#else
  if (rc == EACCES) {
    LOG(WARNING) << "Permission denied. Trying with MDB_NOLOCK ...";
    // Close and re-open environment handle
    mdb_env_close(mdb_env_);
    MDB_CHECK(mdb_env_create(&mdb_env_));
    // Try again with MDB_NOLOCK
    flags |= MDB_NOLOCK;
    MDB_CHECK(mdb_env_open(mdb_env_, source.c_str(), flags, 0664));
  } else {
    MDB_CHECK(rc);
  }
```

So it firstly opens the LMDB using lock by default, and when there is a problem, it retries opening it passing MDB_NOLOCK.

I think the problem maybe in the first mdb_env_open call.
Though GlusterFS implements flock syscall, there is a subtle difference with flock implementation on local filesystem. A process waiting for a flock on GlusterFS file will be turn into "uninterruptible sleep" state, and the process can not handle signals in this state unless it gets the lock. Process waiting for a flock on local file system is in "sleep" state, and we can interrupt it by sending signal.

It seems some subtle flock implementation differences like this would make the first mdb_env_open stuck on GlusterFS, and Caffe do not have the chance to retry opening it without lock.

The problem maybe also in the EACCESS error code. Suppose mdb_env_open would set LOCK_NB flag when calling flock, the error should be be EWOULDBLOCK when there is another process holding the lock, but not EACCESS.

After I change the code to:
```
  if (mode == READ) {
    flags = MDB_RDONLY | MDB_NOTLS;
#ifdef ALLOW_LMDB_NOLOCK
    flags |= MDB_NOLOCK;
#endif
  }
  int rc = mdb_env_open(mdb_env_, source.c_str(), flags, 0664); 
...
```
It does not stuck on GlusterFS any longer.

My questions are:
1. Is it OK to modify the code like above? Does it make any other problems?
2. Is there any tested examples on runing Caffe multinode training using data set on shared file systems such as GlusterFS, NFS or even HDFS?

**Comment by fzou1** [comment] 2017-12-11 08:22
Thank you. We'll look into the patch and evaluate it. But we suggest not to put data set on shared folder since it hurts multinode performance.

**Comment by fzou1** [comment] 2017-12-22 08:13
Could you check permission of lock.mdb is "rw" (read and write)? I cannot reproduce the issue on my cluster, while the dataset is put in shared folder and lock.mdb is set to "rw".

**Comment by fzou1** [comment] 2018-01-19 08:17
We can reproduce this issue on shared FS. The fix will be included in next release. Thank you.

**Closed by fzou1** 2018-01-19 08:17 UTC
