### ISSUE TITLE
There are some errors when I run vgg19 with MKLDNN! Error messages: Check failed: convFwd_pd

### ISSUE THREAD

**Issue by wuzhijiexia** [intel/caffe#103] opened 2017-07-22 08:18 UTC
I need some help!

![image 1](https://user-images.githubusercontent.com/19603119/28489619-55d131f6-6ef9-11e7-88bc-6a6def4fba21.png)

**Comment by guomingz** [comment] 2017-07-27 08:39
Hi Have u solved this issue with the compiled boost?

**Comment by wuzhijiexia** [comment] 2017-07-28 06:59
The problem should not be caused by boost!

**Comment by gtvforever** [comment] 2017-09-27 01:25
Please use the latest intel caffe release for a try. We tested the vgg-19 locally and no issue found.

**Comment by guomingz** [comment] 2017-09-27 01:30
Please use the latest caffe for a try. We couldn't reproduce this issue locally.

**Comment by wuzhijiexia** [comment] 2017-09-27 02:56
Thanks, I will do a try.

**Comment by guomingz** [comment] 2017-09-29 08:19
Hi，wuzhijiexia。  Have u got the similar issue with latest caffe？ If not，we'll close this issue.

**Comment by wzbazinga** [comment] 2017-10-07 07:45
@wuzhijiexia I have met the problem similar to you. I deleted the `engine: MKLDNN` in all layers and put it at the beginning of .prototxt file. It works, but it's slower than MKL2017 and even CAFFE implement.

**Comment by wuzhijiexia** [comment] 2017-10-07 08:18
@guomingz ，if possible, please wait for a few days. The Intel KNL in our lab is broken and is still repaired.

**Comment by wuzhijiexia** [comment] 2017-10-07 08:22
@wzbazinga , what does it mean that putting engine: MKLDNN at the beginning of .prototxt file?

**Comment by wzbazinga** [comment] 2017-10-09 01:26
@wuzhijiexia I am not very sure. I don't known much about Caffe's internal implement. It seems like a default engine configuration for whole network, but every layer can overwrite it. I may be wrong.

**Comment by wuzhijiexia** [comment] 2017-10-10 09:31
@guomingz @wzbazinga 
I got the similar issue with latest caffe!

Meanwhile, I run into a new problem. For the file CMakeList.txt, if I set MKL2017 as an default engine, I don't set MKLDNN as engine for *.prototxt. If I set MKLDNN as an default engine, I don't set MKL2017 as engine for *.prototxt.

According to testing, I deleted the engine: MKLDNN is slower than MKL2017, but faster than CAFFE.

**Comment by wuzhijiexia** [comment] 2017-10-10 11:39
@guomingz @wzbazinga 
I solved the new problem by putting engine: MKLDNN(or MKL2017) at the beginning of .prototxt file when I set the engine: MKLDNN(or MKL2017) for all layers.

**Comment by wzbazinga** [comment] 2017-10-10 13:02
@wuzhijiexia 
`Meanwhile, I run into a new problem. For the file CMakeList.txt, if I set MKL2017 as an default engine, I don't set MKLDNN as engine for *.prototxt. If I set MKLDNN as an default engine, I don't set MKL2017 as engine for *.prototxt.`
Do you mean "can't"? 
I also find that MKLDNN is flower than MKL2017, sometimes even slower than CAFFE.

**Comment by hshen14** [comment] 2017-12-12 09:15
Close it due to no activity in recent months. Please feel free to reopen it if you get the issue again.

**Closed by hshen14** 2017-12-12 09:15 UTC
