### ISSUE TITLE
The speed of forward is significantly different under different caffemodel weights

### ISSUE THREAD

**Issue by smuelpeng** [intel/caffe#139] opened 2017-10-30 05:12 UTC
I trained  a res-18 net  to finish a classification tasks。
Very surprised to find that for the trained model, the network feed forward speed slowed down a lot. (nearly two times slower.)
I carefully examined the occupancy rate of time，
Found that conv1->**dnnexcute**  does slow down  a lot when using my own trained model
I upload the model and prototxt as links below.
https://www.dropbox.com/s/qxf2b86ha6le177/nin.prototxt?dl=0
https://www.dropbox.com/s/yph2pv48x51rbvi/nin.caffemodel?dl=0

I don't know if it's  a common question in CNN training and forward.
But I and my colleagues  meet this problem both, especially on cpu （GPU is too fast to find this problem,as the model is small）

I have been looking for answers for a long time，hoping for your reply soon

**Comment by smuelpeng** [comment] 2017-10-30 07:19
my cpu info: Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz 40 cores
test method:
A:  ./build/tools/caffe  time -engine "MKL2017" -model nin.prototxt
B:  ./build/tools/caffe  time -engine "MKL2017" -model nin.prototxt -weights nin.caffemodel
method B is much slower than A
**P.s.**
I change the caffe.cpp to support trained model speed test as blow:
527   Net<float> caffe_net(FLAGS_model, phase, FLAGS_level, &stages, NULL,
528                        FLAGS_engine);
529   if(FLAGS_weights.size())
530   caffe_net.CopyTrainedLayersFrom(FLAGS_weights);

**Comment by chuanqi129** [comment] 2018-01-12 08:44
Can you still reproduce this issue again now?  I can't reproduce the issue with your description.  In my host, the two methods have similar performance. I attached the two methods' log.
https://www.dropbox.com/s/b9a5hqrv60frhi7/withoutWeights.log?dl=0
https://www.dropbox.com/s/zwyjvk6xf8w912n/withWeights.log?dl=0

**Comment by smuelpeng** [comment] 2018-01-12 09:24
@chuanqi129 several items you may not notice:
1.change the caffe.cpp to make "caffe time" support --weights or caffe will not copy weights from caffemodel.
2.remember to export OMP_NUM_THREADS=1  (which means only one CPU thread use in testing) 
3.CPU type difference.

**Comment by manofmountain** [comment] 2018-05-21 07:28
can you try to use "MKLDNN" as the engine and see if it still exists on your system? Right now we still can't reproduce this issue on our DUT by following your steps.

**Comment by hshen14** [comment] 2018-07-03 08:15
Close it due to no activities recently. Please feel free to reopen it.

**Closed by hshen14** 2018-07-03 08:15 UTC
