### ISSUE TITLE
caffe error

### ISSUE THREAD

**Issue by andreiuc** [intel/caffe#60] opened 2017-03-14 10:57 UTC
Hello,

I am trying to run a Caffe benchmark demo using multinode training but I am encountering 
the following error:

F0101 01:14:29.242821  7694 upgrade_proto.cpp:132] Check failed: ReadProtoFromBinaryFile(param_file, param) Failed to parse NetParameter file: /home/demouser/intelcaffe/models/bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel
*** Check failure stack trace: ***
    @     0x2ac49366ce6d  (unknown)
    @     0x2ac49366eced  (unknown)
    @     0x2ac49366ca5c  (unknown)
    @     0x2ac49366f63e  (unknown)
    @     0x2ac4923697fe  caffe::ReadNetParamsFromBinaryFileOrDie()
    @     0x2ac4922d164a  caffe::Net<>::CopyTrainedLayersFromBinaryProto()
    @     0x2ac4922d16e6  caffe::Net<>::CopyTrainedLayersFrom()
    @     0x2ac48a84fd0c  CopyLayers()
    @     0x2ac48a852578  train()
    @     0x2ac48a84cef7  main
    @     0x2ac4962d0b15  __libc_start_main
    @     0x2ac48a84daad  (unknown)

I have checked that on both systems, the file exists at the indicated path.

Regards,
Andrei

**Comment by michalkuligowski** [comment] 2017-03-17 09:16
Hi,
Can you show the command you run? It looks like file with .caffemodel extension is being read, instead of .protobuf file. The first contains learned weights, the latter - network definition.

**Comment by andreiuc** [comment] 2017-03-17 10:07
Hello,

The command i'm trying to run is:

MLSL_HEAP_SIZE_GB=32 mpirun -v -n 2 -ppn 1 -machinefile /home/demouser/mpd.hosts /home/demouser/intelcaffe/build/tools/caffe train
-solver /home/demouser/dogvscat/dogvscat_solver.prototxt -weights /home/demouser/intelcaffe/models/bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel

Regards,
Andrei

**Comment by michalkuligowski** [comment] 2017-03-17 10:28
Your command looks OK, we'll look into this shortly.

**Comment by fzou1** [comment] 2017-05-05 09:13
bvlc_reference_caffenet.caffemodel may be not correct. Is it trained by yourself or downloaded?

**Comment by andreiuc** [comment] 2017-05-05 14:01
Hello,

The caffe model was downloaded from the following link (it was not trained) :
http://dl.caffe.berkeleyvision.org/bvlc_reference_caffenet.caffemodel

Regards,
Andrei

**Comment by fzou1** [comment] 2017-06-08 03:19
Hi Andrei,
The crash is caused by inconsistent caffemodel with protobuf file. 
The bvlc_reference_caffenet.caffemodel is trained from alexnet topology, and num_output of fc8 (last layer) is 1000. But in protobuf file for dogvscat classification, num_output of fc8 should be 2, right? If so, the caffemodel file cannot be used for finetuning the dogvscat CNN model.

**Comment by hshen14** [comment] 2017-07-18 07:39
Close it as the issue was caused by inconsistent blob size.

**Closed by hshen14** 2017-07-18 07:39 UTC
