### ISSUE TITLE
different performance between ubuntu 16.04 and ubuntu 14.04 ?

### ISSUE THREAD

**Issue by ligongzheng** [intel/caffe#88] opened 2017-06-16 10:03 UTC
I use the caffe tools like this:
~/caffe-master/build/tools/caffe time  -model ./deploy.prototxt -weights mynet.caffemodel 
Then I run it on different ubuntu version. But the performance is weird : no matter what engine I chose,the ubuntu 14.04 is faster than ubuntu 16.04.
I run  another program which was linked against intelCaffe and set the same parameters(include the omp_num_threads), I also get different performance between ubuntu 16.04 and ubuntu 14.04(ubuntu 14.04 is faster again!).
So I wonder if this results is normal ?Does anyone has also encountered this kind of problem ?
If it's normal,Could anyone explain this for me ?

**Comment by etaf** [comment] 2017-06-27 12:46
Hi, @ligongzheng ,
I tried to reproduce the issue by using two docker, one is ubuntu 14.04 and the other is 16.04, there is no performance gap. Can you double check the test environment (both hardware and software) ?

**Comment by hshen14** [comment] 2017-09-27 01:08
Close it as we cannot reproduce the performance gap. Please reopen it when the issue was exposed again.

**Closed by hshen14** 2017-09-27 01:08 UTC
