### ISSUE TITLE
Building for KNL, get not declared in scope errors

### ISSUE THREAD

**Issue by jtchilders** [intel/caffe#31] opened 2016-12-16 02:30 UTC
I'm compiling on a Xeon login node for a 12 node KNL test bed. When building with CMake I get the error:
![image](https://cloud.githubusercontent.com/assets/10742392/21242842/dc405b2e-c2db-11e6-962c-b45da1b5797e.png)

I can't tell if this is a problem with my build or with the repo, which is why I am reporting it. Build details are below.

I've installed:
autoconf-2.69
boost_1_62_0
cmake-3.7.1
gflags-2.2.0
glog-0.3.4
hdf5-1.8.18
leveldb-1.19
lmdb-LMDB_0.9.18
mpich-3.2
OpenBLAS-0.2.19
opencv-2.4.13
protobuf-3.1.0
snappy-1.1.3

I'm using a native version of gcc 4.8.5 installed on a RHEL 7.2 system.

'git describe --tags' reports:
self_containted_MKLGOLD_u1-82-g37c8170

My cmake command is pretty big, but tells it where to find all my installs as most of the FindX.cmake files fail for me.

OpenBLAS_HOME=$HOME/tools/OpenBLAS-0.2.19 CXX=mpicxx \
cmake \
-DCPU_ONLY=1 \
-DUSE_MPI=1 \
-DBLAS=open \
-DCMAKE_INSTALL_PREFIX=$HOME/caffe/caffe/install \
-DBoost_INCLUDE_DIR=$HOME/tools/boost_1_62_0/install/include \
-DGFLAGS_ROOT_DIR=$HOME/tools/gflags-2.2.0/install \
-DGFLAGS_LIBRARY=$HOME/tools/gflags-2.2.0/install/lib \
-DGFLAGS_INCLUDE_DIR=$HOME/tools/gflags-2.2.0/install/include \
-DGLOG_INCLUDE_DIR=$HOME/tools/glog-0.3.4/install/include \
-DGLOG_LIBRARY=$HOME/tools/glog-0.3.4/install/lib \
-DProtobuf_INCLUDE_DIR=$HOME/tools/protobuf-3.1.0/install/include \
-DProtobuf_LIBRARY=$HOME/tools/protobuf-3.1.0/install/lib \
-DHDF5_C_LIBRARY_hdf5=$HOME/tools/hdf5-1.8.18/install/lib/libhdf5.so \
-DHDF5_DIR=$HOME/tools/protobuf-3.1.0/ \
-DHDF5_C_LIBRARY_hdf5_hl=$HOME/tools/hdf5-1.8.18/install/lib/libhdf5_hl.so \
-DHDF5_CXX_COMPILER_EXECUTABLE=$HOME/tools/hdf5-1.8.18/install/bin/h5c++ \
-DHDF5_CXX_LIBRARY_hdf5=$HOME/tools/hdf5-1.8.18/install/lib/libhdf5.so \
-DHDF5_CXX_LIBRARY_hdf5_cpp=$HOME/tools/hdf5-1.8.18/install/lib/libhdf5_cpp.so \
-DHDF5_CXX_LIBRARY_hdf5_hl=$HOME/tools/hdf5-1.8.18/install/lib/libhdf5_hl.so \
-DHDF5_CXX_LIBRARY_hdf5_hl_cpp=$HOME/tools/hdf5-1.8.18/install/lib/libhdf5_hl_cpp.so \
-DHDF5_DIR=$HOME/tools/hdf5-1.8.18 \
-DLMDB_INCLUDE_DIR=$HOME/tools/lmdb-LMDB_0.9.18/install/include \
-DLMDB_LIBRARIES=$HOME/tools/lmdb-LMDB_0.9.18/install/lib \
-DLevelDB_INCLUDE=$HOME/tools/leveldb-1.19/include \
-DLevelDB_LIBRARY=$HOME/tools/leveldb-1.19/out-shared \
-DSnappy_INCLUDE_DIR=$HOME/tools/snappy-1.1.3/install/include \
-DSnappy_LIBRARIES=$HOME/tools/snappy-1.1.3/install/lib \
-DOpenCV_LIB_DIR_OPT=$HOME/tools/opencv-2.4.13/install/lib \
-DOpenCV_LIB_DIR_DBG=$HOME/tools/opencv-2.4.13/install/lib  \
-DCMAKE_C_FLAGS="-I/home/jchilders/tools/install/include" \
-DCMAKE_CXX_FLAGS="-I/home/jchilders/tools/install/include" \
-DCMAKE_EXE_LINKER_FLAGS="-L/home/jchilders/tools/install/lib  -lprotobuf -lprotoc -lopencv_core -lopencv_calib3d -lopencv_contrib -lopencv_features2d -lopencv_flann -lopencv_highgui -lopencv_imgproc -lopencv_legacy -lopencv_ml -lopencv_nonfree -lopencv_objdetect -lopencv_ocl -lopencv_photo -lopencv_stitching -lopencv_superres -lopencv_video -lopencv_videostab -lhdf5_cpp -lhdf5_hl_cpp -lhdf5_hl -lhdf5 -lglog -lgflags  -lleveldb -llmdb" \
-DCMAKE_MODULE_LINKER_FLAGS="-L/home/jchilders/tools/install/lib  -lprotobuf -lprotoc -lopencv_core -lopencv_calib3d -lopencv_contrib -lopencv_features2d -lopencv_flann -lopencv_highgui -lopencv_imgproc -lopencv_legacy -lopencv_ml -lopencv_nonfree -lopencv_objdetect -lopencv_ocl -lopencv_photo -lopencv_stitching -lopencv_superres -lopencv_video -lopencv_videostab -lhdf5_cpp -lhdf5_hl_cpp -lhdf5_hl -lhdf5 -lglog -lgflags -leveldb -llmdb" \
-DCMAKE_SHARED_LINKER_FLAGS="-L/home/jchilders/tools/install/lib -lprotobuf -lprotoc -lopencv_core -lopencv_calib3d -lopencv_contrib -lopencv_features2d -lopencv_flann -lopencv_highgui -lopencv_imgproc -lopencv_legacy -lopencv_ml -lopencv_nonfree -lopencv_objdetect -lopencv_ocl -lopencv_photo -lopencv_stitching -lopencv_superres -lopencv_video -lopencv_videostab -lhdf5_cpp -lhdf5_hl_cpp -lhdf5_hl -lhdf5 -lglog -lgflags -lleveldb -llmdb"  ..

Then I run make, but get the error above.

**Comment by jtchilders** [comment] 2016-12-16 16:48
I found this post:
http://mingw-w64-public.narkive.com/0yRqe2R8/problem-with-cpuid-when-compiling-xerces-c-3-1-0
I wonder if you have a similar issue? Are you including <intrin.h> prior to the <cpuid.h> included in the file "xbyak/xbyak_util.h" ?

**Comment by michalkuligowski** [comment] 2016-12-20 09:59
Thanks very much for your report, we are working on reproducing your problem and will reply to you as soon as we find a solution

**Comment by apwojcik** [comment] 2017-01-12 15:35
Intel Distribution of Caffe switched to Intel(R) Machine Learning Scaling Library (MLSL) in order to provide multi-node training functionality. Pure MPI multi-node solution is experimental code only and we have no plans to continue development on it. This means future releases of Intel Distribution of Caffe may brake or even remove pure Intel MPI multi-node. Please update to latest master branch of Intel Caffe and follow [this instruction](https://github.com/intel/caffe/wiki/Multinode-guide) which shall explain you how to prepare to and how to build the latest Intel Caffe with MLSL. Plase note this is MLSL Beta version, full Gold quality is expected end of Q1'2017. Let us know if you need more information or have issues building/funning latest Intel Caffe MN.

**Comment by moting9** [comment] 2017-01-13 01:34
@apwojcik  Hello, I try to run distributed resnet50 with mlsl, but failied due to MAX_COMPUTE_OP defined in mlsl is 400 and too small to run resnet50. 

(106827): /localdisk/jenkins/mlsl-build/src/mlsl_impl.h:ComputeOpImpl:568: ASSERT 'op_count < MAX_COMPUTE_OP' FAILED: too many operations (current count 400, limit 400)

This should be mlsl library issue. We hope to run distributed resnet 50 and even resnet101 with  intel caffe. 
Thanks for paying attention to this issue.

**Comment by vcodreanu** [comment] 2017-02-07 14:01
Any updates on the MAX_COMPUTE_OP issue? I also encounter it with distributed training of googlenet_v2.

**Comment by apwojcik** [comment] 2017-02-09 10:13
The MAX_COMPUTE_OP will be fixed in MLSL 2017 Gold release planed end of Q1'17.

**Closed** 2017-02-14 08:12 UTC
