### ISSUE TITLE
MPI error

### ISSUE THREAD

**Issue by fastalgo** [intel/caffe#123] opened 2017-09-28 00:58 UTC
**I installed Intel Caffe on our local cluster. But when I ran it, I got this error:**

Unidentified node: Error detected by libibgni.so.  Subsequent operation may be unreliable.  IAA did not recognize this as an MPI process
Unidentified node: Error detected by libibgni.so.  Subsequent operation may be unreliable.  IAA did not recognize this as an MPI process
Unidentified node: Error detected by libibgni.so.  Subsequent operation may be unreliable.  IAA did not recognize this as an MPI process
Unidentified node: Error detected by libibgni.so.  Subsequent operation may be unreliable.  IAA did not recognize this as an MPI process
Unidentified node: Error detected by libibgni.so.  Subsequent operation may be unreliable.  IAA did not recognize this as an MPI process
Unidentified node: Error detected by libibgni.so.  Subsequent operation may be unreliable.  IAA did not recognize this as an MPI process
Unidentified node: Error detected by libibgni.so.  Subsequent operation may be unreliable.  IAA did not recognize this as an MPI process
Unidentified node: Error detected by libibgni.so.  Subsequent operation may be unreliable.  IAA did not recognize this as an MPI process
nid06489:SCM:22fc4:aab49500: 127246108 us(127246108 us!!!):  open_hca: failed to init cr pipe - Connection timed out
nid06488:SCM:230fc:aab49500: 127247577 us(127247577 us!!!):  open_hca: failed to init cr pipe - Connection timed out
nid06490:SCM:234fd:aab49500: 127254040 us(127254040 us!!!):  open_hca: failed to init cr pipe - Connection timed out
Unidentified node: Error detected by libibgni.so.  Subsequent operation may be unreliable.  IAA did not recognize this as an MPI process
Unidentified node: Error detected by libibgni.so.  Subsequent operation may be unreliable.  IAA did not recognize this as an MPI process
Unidentified node: Error detected by libibgni.so.  Subsequent operation may be unreliable.  IAA did not recognize this as an MPI process
nid06487:SCM:234f0:aab49500: 127301301 us(127301301 us!!!):  open_hca: failed to init cr pipe - Connection timed out
Unidentified node: Error detected by libibgni.so.  Subsequent operation may be unreliable.  IAA did not recognize this as an MPI process
nid06489:SCM:22fc4:aab49500: 127206889 us(127206889 us!!!):  open_hca: failed to init cr pipe - Connection timed out
nid06488:SCM:230fc:aab49500: 127209830 us(127209830 us!!!):  open_hca: failed to init cr pipe - Connection timed out
nid06490:SCM:234fd:aab49500: 127208621 us(127208621 us!!!):  open_hca: failed to init cr pipe - Connection timed out

**Comment by fzou1** [comment] 2017-09-28 07:57
May I know how you run intel caffe? did you export MPI macro: I_MPI_FABRICS=ofi? suggest to run scripts/run_intelcaffe.sh or use the macros defined in the script.

**Comment by fastalgo** [comment] 2017-09-28 23:35
I have solved that issue. Because our machine was made by Cray, so I have to use Cray MPI.
Now I got a new problem:

caffe: symbol lookup error: caffe: undefined symbol: _ZN5caffe9MultiSyncIfEC1EN5boost10shared_ptrINS_6SolverIfEEEE

**Comment by fzou1** [comment] 2017-11-02 02:29
The issue is fixed. right? can we close it?

**Comment by fastalgo** [comment] 2017-11-02 02:40
Please close it

**Closed** 2017-11-02 02:42 UTC
